"""Shared palette + canvas conventions for every Fig. 1 component.

Do not edit this file without updating all components. Every component module
must expose a single entry point:

    draw(ax, x, y, w, h, **kwargs) -> dict

`(x, y, w, h)` is the rectangle the component must fill, given in the *data
coordinates* of the caller's Axes. The component must:
  * not call set_xlim/set_ylim/axis/savefig/tight_layout,
  * not create figures,
  * keep every artist inside [x, x+w] x [y, y+h],
  * return a dict, optionally carrying anchors, e.g. {"cut_x": ...}.
"""

# ---------------------------------------------------------------- palette
INK = "#1c2730"        # primary text / hard geometry
SUB = "#65737e"        # secondary text
GRID = "#cbd5db"       # hairlines
BLUE = "#3b82bb"       # available target data  C_s
BLUE2 = "#7caed3"
BLUE_LT = "#e7f0f8"
ORANGE = "#c87835"     # reserved target data   T_s
ORANGE2 = "#d99a61"
ORANGE_LT = "#faecdf"
DARK = "#405565"       # source training 80%
DARK2 = "#5b7183"
LIGHT = "#a9b6bd"      # source checkpoint-selection 20%
LIGHT2 = "#c4ced4"
SOFT = "#f3f6f7"
GREEN = "#4b8d76"
PAPER = "#ffffff"

# every connector in the figure is this one blue-grey, whatever it carries
ARROW = "#4f6b7d"

# per-trial class cue colours used inside the stripes
CLASS_COLORS = ["#2f80b7", "#50a884", "#d98b3a", "#bd5b62"]

# heatmap ramp for the decoder planes: pale blue -> white
HEAT_LO = "#a8cae4"
HEAT_HI = "#ffffff"

# shared deterministic seed so every component is reproducible
SEED = 20260923
